const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.scrollto,
		C3.Behaviors.Physics,
		C3.Plugins.Particles,
		C3.Behaviors.aekiroWater,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Behaviors.skymenTrail,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.TextBox.Exps.Text,
		C3.ScriptsInEvents.Ev_tools_Event6_Act1,
		C3.ScriptsInEvents.Ev_tools_Event8_Act1,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.System.Exps.layoutscale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Particles.Exps.XRandom,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.ScriptsInEvents.Ev_game_Event1_Act7,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Behaviors.Physics.Exps.Density,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.aekiroWater.Acts.applyForce,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Audio.Acts.PlayAtObjectByName,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.BBoxMidY,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.skymenTrail.Acts.SetLength,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.Particles.Cnds.PickByUID,
		C3.Plugins.Particles.Exps.InitSpeed,
		C3.Plugins.Particles.Exps.Rate,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetRate,
		C3.ScriptsInEvents.Ev_sdk_Event1_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event4_Act2,
		C3.ScriptsInEvents.Ev_sdk_Event10_Act2,
		C3.ScriptsInEvents.Ev_sdk_Event29_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event32_Act3,
		C3.ScriptsInEvents.Ev_sdk_Event55_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event63_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event66_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event69_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event73_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event77_Act2,
		C3.ScriptsInEvents.Ev_sdk_Event78_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event81_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event84_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event84_Act2,
		C3.ScriptsInEvents.Ev_sdk_Event85_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event85_Act2,
		C3.ScriptsInEvents.Ev_sdk_Event87_Act1,
		C3.ScriptsInEvents.Ev_sdk_Event88_Act1
	];
};
self.C3_JsPropNameTable = [
	{function: 0},
	{button_enabled: 0},
	{sound_click: 0},
	{volume: 0},
	{button_template: 0},
	{type: 0},
	{inputText: 0},
	{ENABLED: 0},
	{originalX: 0},
	{originalY: 0},
	{originalWidth: 0},
	{originalHeight: 0},
	{time: 0},
	{moveAmount: 0},
	{Sinousidal: 0},
	{InOutBack: 0},
	{Direction_In: 0},
	{Direction_Out: 0},
	{orderNr: 0},
	{customDelay: 0},
	{sound_in: 0},
	{sound_out: 0},
	{customDetails: 0},
	{Box_transition_Template: 0},
	{Element_transition_Sprite_Template: 0},
	{Element_transition_9Patch_Template: 0},
	{text_general: 0},
	{line_arrow_player: 0},
	{line_arrow_touch: 0},
	{ERBA: 0},
	{angleDiffForRotate: 0},
	{Sprite: 0},
	{arrow_player: 0},
	{arrow_touch: 0},
	{Rotate: 0},
	{wall_circle: 0},
	{Sine: 0},
	{wall_movable: 0},
	{wall_orbit: 0},
	{FrecciaDx: 0},
	{FrecciaSx: 0},
	{home_legno: 0},
	{lucchetto: 0},
	{ButtonPlay: 0},
	{skin_button_frame: 0},
	{skin_ombra: 0},
	{TastoSKin_home: 0},
	{DisplacementFollowPoint_X: 0},
	{DisplacementFollowPoint_Y: 0},
	{Displacement_X: 0},
	{Displacement_Y: 0},
	{Tween: 0},
	{Torta: 0},
	{nr: 0},
	{tweenTimeScorrimento: 0},
	{skin_button_bg: 0},
	{button_bg_: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{TimelineController: 0},
	{Nuvola_: 0},
	{tile_mountains_1: 0},
	{TiledBackground: 0},
	{AJAX: 0},
	{api_data: 0},
	{api_temp: 0},
	{save: 0},
	{Button_Audio: 0},
	{Button_rigioca: 0},
	{home_fascio: 0},
	{player_sprite: 0},
	{ScrollTo: 0},
	{camnera: 0},
	{TastoSkin: 0},
	{skin_selection_page_Pivot: 0},
	{camera_game: 0},
	{Physics: 0},
	{coll_player: 0},
	{scale: 0},
	{camera_scale: 0},
	{camera_game_second: 0},
	{SineHeight: 0},
	{SineWidth: 0},
	{Torta_game: 0},
	{polaroid: 0},
	{Button_Continue: 0},
	{button_small_bg: 0},
	{raggio: 0},
	{unlock_bar_empty: 0},
	{unlock_bar_full: 0},
	{unlocking_frame: 0},
	{Cesto: 0},
	{Unlock_frutto_: 0},
	{unlocking_frame_mask: 0},
	{mask_raggi_complete: 0},
	{bagliore_polaroid: 0},
	{particle_stars: 0},
	{particle_stars_speed: 0},
	{ad_card: 0},
	{ad_oggetto: 0},
	{ad_lucchetto: 0},
	{ad_reward_banner: 0},
	{ad_reward_button: 0},
	{ad_ombra: 0},
	{particle_ad: 0},
	{speed: 0},
	{Water: 0},
	{water: 0},
	{bounceCount: 0},
	{phi_box: 0},
	{phi_cesto: 0},
	{phi_frutta: 0},
	{particles_selected_skin: 0},
	{PlatformInfo: 0},
	{rimbalzino: 0},
	{icon_cesto: 0},
	{LocalStorage: 0},
	{json_save: 0},
	{coriandoli_: 0},
	{particle_coriandoli: 0},
	{water_bg: 0},
	{particle_splash: 0},
	{TrailRenderer: 0},
	{scia: 0},
	{Sine2: 0},
	{Titolo: 0},
	{tiled_texture_1: 0},
	{lianeMuro: 0},
	{alghe: 0},
	{particle_bolle_alghr: 0},
	{completed: 0},
	{tutorial_box: 0},
	{tutorial_1: 0},
	{CoolmathGames600x: 0},
	{dir: 0},
	{spect_destination_X: 0},
	{spect_destination_y: 0},
	{Camera: 0},
	{Tween_button: 0},
	{f_button: 0},
	{f_input_texts: 0},
	{Box_Tween: 0},
	{f_Box_transition: 0},
	{f_Element_transition_sprite: 0},
	{f_Element_transition_9Patch: 0},
	{f_Element_transition_text: 0},
	{Timer: 0},
	{players: 0},
	{SineH: 0},
	{SineV: 0},
	{Nuvole: 0},
	{walls: 0},
	{phisycs_objects: 0},
	{functions: 0},
	{username: 0},
	{email: 0},
	{password: 0},
	{name: 0},
	{surname: 0},
	{sesso: 0},
	{birthdate: 0},
	{phone: 0},
	{address: 0},
	{city: 0},
	{province: 0},
	{postalcode: 0},
	{country: 0},
	{privacy: 0},
	{commercial: 0},
	{profilation: 0},
	{institute: 0},
	{f_uid: 0},
	{score: 0},
	{customprop: 0},
	{limit: 0},
	{customRank: 0},
	{position: 0},
	{UID_p: 0},
	{details: 0},
	{key: 0},
	{otpcode: 0},
	{destinatario: 0},
	{pssw: 0},
	{original_viewportwidth: 0},
	{original_viewportheight: 0},
	{transizione_attiva: 0},
	{enter: 0},
	{exit: 0},
	{instaOut: 0},
	{instaIn: 0},
	{duration: 0},
	{value: 0},
	{amount: 0},
	{massimo: 0},
	{minimo: 0},
	{result: 0},
	{string: 0},
	{array: 0},
	{pickUID: 0},
	{InOut: 0},
	{waitTime: 0},
	{PickByCustomDetails: 0},
	{layerName: 0},
	{elementsCount: 0},
	{delay: 0},
	{TransitionDuration: 0},
	{DefaultDirection: 0},
	{ForOrderNr: 0},
	{OrderAscending: 0},
	{OrderDescending: 0},
	{HideLayerAfter_Out: 0},
	{MUSIC: 0},
	{MASTER: 0},
	{SFX: 0},
	{VolumeEffects: 0},
	{VolumeMusic: 0},
	{SFX_: 0},
	{MUSIC_: 0},
	{MASTER_: 0},
	{directlyToSkinPage: 0},
	{firstEnter: 0},
	{skinMax: 0},
	{skin_unlocked: 0},
	{skin_selected: 0},
	{level_reached: 0},
	{level_avaibles: 0},
	{wait: 0},
	{playerUID: 0},
	{skin_page: 0},
	{pageNr: 0},
	{followSpeed: 0},
	{level_actual: 0},
	{GameplayActive: 0},
	{maxShotPower: 0},
	{breakADCounter: 0},
	{dragging: 0},
	{angleDirection: 0},
	{power: 0},
	{maxDistancePower: 0},
	{startingPointX: 0},
	{startingPointY: 0},
	{endingPointX: 0},
	{endingPointY: 0},
	{force_distance: 0},
	{directionAngle: 0},
	{cameraScaleDestination: 0},
	{marginMax: 0},
	{physics_objs_max_bounce: 0},
	{player_bounce_count: 0},
	{unlockNecessary: 0},
	{unlockProgress: 0},
	{unlockAdCounter: 0},
	{experenceGainAmount: 0},
	{sdk_GamePix: 0},
	{sdk_CrazyGames: 0},
	{sdk_Poki: 0},
	{GATO: 0},
	{AUDIO: 0},
	{CoolMath: 0},
	{coolMathIsRewarded: 0},
	{success: 0},
	{coolmathRewardTag: 0},
	{RewardTag: 0},
	{rewardActual: 0},
	{reward: 0},
	{succes: 0},
	{width: 0},
	{height: 0},
	{IdBanner: 0},
	{X: 0},
	{Y: 0},
	{"728x90": 0},
	{"300x250": 0},
	{"320x50": 0},
	{"468x60": 0},
	{"320x100": 0},
	{intensityForPoki: 0},
	{SDK_invite_URL: 0},
	{paramName: 0},
	{uri: 0},
	{R: 0},
	{domain: 0},
	{PROD: 0},
	{GID: 0},
	{API_url: 0},
	{UID: 0},
	{sendGiocoAperto: 0},
	{SendInitialTrack: 0},
	{IsLogged: 0}
];

self.InstanceType = {
	button_template: class extends self.ISpriteInstance {},
	inputText: class extends self.ITextInputInstance {},
	Box_transition_Template: class extends self.ISpriteInstance {},
	Element_transition_Sprite_Template: class extends self.ISpriteInstance {},
	Element_transition_9Patch_Template: class extends self.IWorldInstance {},
	text_general: class extends self.ITextInstance {},
	line_arrow_player: class extends self.ITiledBackgroundInstance {},
	line_arrow_touch: class extends self.ITiledBackgroundInstance {},
	ERBA: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	arrow_player: class extends self.ISpriteInstance {},
	arrow_touch: class extends self.ISpriteInstance {},
	wall_circle: class extends self.ISpriteInstance {},
	wall_movable: class extends self.ISpriteInstance {},
	wall_orbit: class extends self.ISpriteInstance {},
	FrecciaDx: class extends self.ISpriteInstance {},
	FrecciaSx: class extends self.ISpriteInstance {},
	home_legno: class extends self.ITiledBackgroundInstance {},
	lucchetto: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	skin_button_frame: class extends self.ISpriteInstance {},
	skin_ombra: class extends self.ISpriteInstance {},
	TastoSKin_home: class extends self.ISpriteInstance {},
	Torta: class extends self.ISpriteInstance {},
	skin_button_bg: class extends self.ISpriteInstance {},
	button_bg_: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Nuvola_: class extends self.ISpriteInstance {},
	tile_mountains_1: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	api_data: class extends self.IJSONInstance {},
	api_temp: class extends self.IJSONInstance {},
	save: class extends self.IJSONInstance {},
	Button_Audio: class extends self.ISpriteInstance {},
	Button_rigioca: class extends self.ISpriteInstance {},
	home_fascio: class extends self.ITiledBackgroundInstance {},
	player_sprite: class extends self.ISpriteInstance {},
	camnera: class extends self.ISpriteInstance {},
	TastoSkin: class extends self.ISpriteInstance {},
	skin_selection_page_Pivot: class extends self.ISpriteInstance {},
	camera_game: class extends self.ISpriteInstance {},
	coll_player: class extends self.ISpriteInstance {},
	camera_scale: class extends self.ISpriteInstance {},
	camera_game_second: class extends self.ISpriteInstance {},
	Torta_game: class extends self.ISpriteInstance {},
	polaroid: class extends self.ISpriteInstance {},
	Button_Continue: class extends self.ISpriteInstance {},
	button_small_bg: class extends self.ISpriteInstance {},
	raggio: class extends self.ISpriteInstance {},
	unlock_bar_empty: class extends self.ISpriteInstance {},
	unlock_bar_full: class extends self.ITiledBackgroundInstance {},
	unlocking_frame: class extends self.ISpriteInstance {},
	Cesto: class extends self.ISpriteInstance {},
	Unlock_frutto_: class extends self.ISpriteInstance {},
	unlocking_frame_mask: class extends self.ISpriteInstance {},
	mask_raggi_complete: class extends self.ISpriteInstance {},
	bagliore_polaroid: class extends self.ISpriteInstance {},
	particle_stars: class extends self.IParticlesInstance {},
	particle_stars_speed: class extends self.IParticlesInstance {},
	ad_card: class extends self.ISpriteInstance {},
	ad_oggetto: class extends self.ISpriteInstance {},
	ad_lucchetto: class extends self.ISpriteInstance {},
	ad_reward_banner: class extends self.ISpriteInstance {},
	ad_reward_button: class extends self.ISpriteInstance {},
	ad_ombra: class extends self.ISpriteInstance {},
	particle_ad: class extends self.IParticlesInstance {},
	speed: class extends self.ITiledBackgroundInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	phi_box: class extends self.ISpriteInstance {},
	phi_cesto: class extends self.ISpriteInstance {},
	phi_frutta: class extends self.ISpriteInstance {},
	particles_selected_skin: class extends self.IParticlesInstance {},
	PlatformInfo: class extends self.IInstance {},
	rimbalzino: class extends self.ISpriteInstance {},
	icon_cesto: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	json_save: class extends self.IJSONInstance {},
	coriandoli_: class extends self.ISpriteInstance {},
	particle_coriandoli: class extends self.IParticlesInstance {},
	water_bg: class extends self.ITiledBackgroundInstance {},
	particle_splash: class extends self.IParticlesInstance {},
	scia: class extends self.ISpriteInstance {},
	Titolo: class extends self.ISpriteInstance {},
	tiled_texture_1: class extends self.ITiledBackgroundInstance {},
	lianeMuro: class extends self.ISpriteInstance {},
	alghe: class extends self.ISpriteInstance {},
	particle_bolle_alghr: class extends self.IParticlesInstance {},
	completed: class extends self.ISpriteInstance {},
	tutorial_box: class extends self.IWorldInstance {},
	tutorial_1: class extends self.ISpriteInstance {},
	CoolmathGames600x: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	f_button: class extends self.ISpriteInstance {},
	f_input_texts: class extends self.ITextInputInstance {},
	f_Box_transition: class extends self.ISpriteInstance {},
	f_Element_transition_sprite: class extends self.ISpriteInstance {},
	f_Element_transition_9Patch: class extends self.IWorldInstance {},
	f_Element_transition_text: class extends self.ITextInstance {},
	players: class extends self.ISpriteInstance {},
	Nuvole: class extends self.ISpriteInstance {},
	walls: class extends self.ISpriteInstance {},
	phisycs_objects: class extends self.ISpriteInstance {}
}